# Build and serve an Angular frontend application using NGINX
FROM node:20-alpine AS build
WORKDIR /app

# Copy package.json and package-lock.json first to leverage Docker cache
COPY ../../frontend/package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the source
COPY ../../frontend .

# pass version calculated in github action into assets before building
ARG APP_VERSION=0.0.0
RUN echo "{\"version\": \"${APP_VERSION}\"}" > /app/src/assets/version.json

# Build Angular app
RUN npm run build --output-path=dist --configuration=production --aot --build-optimizer --vendor-chunk --source-map=false

# Stage 2: serve
FROM docker.io/almalinux:9

# install Nginx and clean the cache to keep the image slim
RUN dnf install -y nginx && \
    dnf clean all

# remove default nginx config and add your custom one
RUN rm -f /etc/nginx/conf.d/default.conf /etc/nginx/nginx.conf
COPY docker/frontend/nginx/nginx.conf /etc/nginx/nginx.conf

# Copy built Angular app to NGINX html folder
COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html

# Expose port
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]