import json
from datetime import timedelta

from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils import timezone
from rest_api.workflow.models import Workflow
from rest_framework import status
from rest_framework.test import APISimpleTestCase

User = get_user_model()


class WorkflowTests(APISimpleTestCase):
    databases = {"default"}

    @classmethod
    def setUpClass(cls):
        # query DB for latest workflow to use in tests
        cls.test_data = {
            "workflow_id": -1,
            "creation_time": timezone.now() - timedelta(days=1),
        }
        # get last job
        raw_obj = Workflow.objects.order_by("-workflow_id").first()
        if raw_obj:
            cls.test_data["workflow_id"] = raw_obj.workflow_id
            cls.test_data["creation_time"] = raw_obj.creation_time

        print("[WorkflowTests] Test data for views:", cls.test_data)

    def setUp(self):
        """Get the last object from existing database and force auth for client."""
        # force authentication on the DRF test client with test user
        self.user, _ = User.objects.get_or_create(username="testuser")
        self.client.force_authenticate(user=self.user)

    def test_workflow_list_view(self):
        url = reverse("workflow-list", kwargs={"version": "v1"})
        hours = int(((timezone.now() - self.test_data["creation_time"]).total_seconds() + 600) / 60 / 60) if self.test_data["creation_time"] else 24
        response = self.client.get(url, {"hours": hours})
        self.assertEqual(response.status_code, status.HTTP_200_OK)

        # inspect headers generated by FilterMetadataHeaderMixin
        self.assertIn("X-Applied-Filters", response)
        self.assertIn("X-Ignored-Filters", response)

        applied_filters = json.loads(response["X-Applied-Filters"])
        self.assertEqual(applied_filters.get("hours"), hours)

        # verify structure of returned data from real DB
        if isinstance(response.data, dict):
            results = response.data.get("results", [])
        else:
            results = response.data
        self.assertIsInstance(results, list)

        if len(results) > 0:
            first_row = results[0]
            # Ensure aggregated keys exist on real database records
            self.assertIn("workflow_id", first_row)
            self.assertIn("total_steps", first_row)
            self.assertIn("pending_steps", first_row)
            self.assertIn("active_steps", first_row)
            self.assertIn("completed_steps", first_row)
            self.assertIn("failed_steps", first_row)
            self.assertIn("total_data_items", first_row)

            print(
                f"[WorkflowTests] Workflow {first_row['workflow_id']} | "
                f"Steps: {first_row['total_steps']}: "
                f" {first_row['pending_steps']} pending, {first_row['active_steps']} active,"
                f" {first_row['completed_steps']} completed, {first_row['failed_steps']} failed |"
                f" Data items: {first_row['total_data_items']}"
            )

    def test_workflow_detail_view(self):
        url = reverse("workflow-detail", kwargs={"version": "v1", "workflow_id": self.test_data["workflow_id"]})
        response = self.client.get(url, {})
        self.assertEqual(response.status_code, status.HTTP_200_OK)

        # assert fields
        data_raw = response.data
        self.assertIsInstance(data_raw, dict)
        self.assertEqual(data_raw["workflow_id"], self.test_data["workflow_id"])
        self.assertIn("steps", data_raw)
        self.assertIn("file_summary", data_raw)
        self.assertIn("data_items", data_raw)

        print(data_raw)
